
clear;

%% シミュレーションのパラメータ
global tspan x0
tspan = [0, 5];
x0 = [0; 0; pi/6; 0];

%% 倒立振子のパラメータ
global M m l D_x D_theta g
M = 1;
m = 0.7;
l = 0.1;
D_x = 0.01;
D_theta = 0.01;
g = 9.80665;

%% シミュレーション実行
[t, x, name] = LQR();


%% プロット

fig0 = figure();
subplot(2, 2, 1);
plot(t, x(:, 1));
xlabel('time t');
ylabel('x [m]')
legend('x');
title(name);
grid on

subplot(2, 2, 2);
plot(t, x(:, 2));
xlabel('time t');
ylabel('v [m/s]')
legend('v');
title(name);
grid on

subplot(2, 2, 3);
plot(t, x(:, 3));
xlabel('time t');
ylabel('theta [rad]')
legend('theta');
title(name);
grid on

subplot(2, 2, 4);
plot(t, x(:, 4));
xlabel('time t');
ylabel('omega [rad/s]')
legend('omega');
title(name);
grid on

%% アニメーション
% データ作成
xdata = [x(:, 1) x(:, 1)+2*l*cos(pi/2-x(:, 3))];
ydata = [zeros(length(t), 1) 2*l*sin(pi/2-x(:, 3))];

% アニメ作成

fig = figure;

frames(length(t)) = struct('cdata', [], 'colormap', []);
xlim([-3*l 3*l]);
ylim([-2.2*l 2.2*l]);
xlabel('x [m]');
ylabel('y [m]');
grid on
axis equal
hold on
p = plot(xdata(1, :), ydata(1, :));
tx = text(0, -0.1, "0");

hold off

axis equal


for i = 1:length(t)
    set(tx, 'String',num2str(t(i),'%.02f'));
    p.XData = xdata(i, :);
    p.YData = ydata(i, :);
    drawnow;
    frames(i) = getframe(fig);
end

video = VideoWriter('lqr.mp4', 'MPEG-4');
open(video);
writeVideo(video, frames);
close(video);

%% LQR
function [t, x, name] = LQR
%LQRで制御

name = 'LQR';

global tspan x0
global M m l D_x D_theta g

%システムのA,B行列
q2 = 0;
q3 = 0;
q4 = 0;
sysA = A(D_theta,D_x,M,g,l,m,q2,q3,q4);
sysB = B(M,l,m,q3);

% 重み行列
Q =  diag([10.0, 0, 100, 0]);
R = 0.01;

% リカッチ方程式を解く
S = [];
E = [];
G = [];

[~, K, ~] = icare(sysA, sysB, Q, R, S, E, G);

    function dx = lqrODE(t, x)
        u = -K * x;
        dx = Fxu(D_theta,D_x,M,g,l,m,x(2,1),x(3,1),x(4,1),u);
    end

% シミュレーション実行
[t, x] = ode45(@lqrODE, tspan, x0);
        
end


%% 振り子のモデル式
function Fxu = Fxu(D_theta,D_x,M,g,l,m,q2,q3,q4,u)
%FXU
%    FXU = FXU(D_THETA,D_X,M,G,L,M,Q2,Q3,Q4,U)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    11-Feb-2022 22:15:12

t2 = cos(q3);
t3 = sin(q3);
t4 = M.*4.0;
t5 = l.^2;
t6 = m.*4.0;
t7 = m.^2;
t8 = q3.*2.0;
t9 = q4.^2;
t10 = t2.^2;
t11 = sin(t8);
t12 = m.*t10.*3.0;
t13 = -t12;
t14 = t4+t6+t13;
t15 = 1.0./t14;
Fxu = [q2;(t15.*(l.*u.*4.0-D_x.*l.*q2.*4.0+D_theta.*q4.*t2.*3.0-g.*l.*m.*t11.*(3.0./2.0)+t3.*t5.*t6.*t9-l.*m.*q2.*q4.*t11.*(3.0./2.0)))./l;q4;(t15.*(-D_theta.*M.*q4-D_theta.*m.*q4+g.*l.*t3.*t7-l.*m.*t2.*u-(t5.*t7.*t9.*t11)./2.0+M.*g.*l.*m.*t3+D_x.*l.*m.*q2.*t2+l.*q2.*q4.*t3.*t7+M.*l.*m.*q2.*q4.*t3).*3.0)./(m.*t5)];
end

function A = A(D_theta,D_x,M,g,l,m,q2,q3,q4)
%A
%    A = A(D_THETA,D_X,M,G,L,M,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    11-Feb-2022 22:15:13

t2 = cos(q3);
t3 = sin(q3);
t4 = M.*4.0;
t5 = l.^2;
t6 = m.*4.0;
t7 = m.^2;
t8 = q3.*2.0;
t9 = q4.^2;
t13 = 1.0./l;
t15 = 1.0./m;
t10 = cos(t8);
t11 = t2.^2;
t12 = sin(t8);
t14 = 1.0./t5;
t16 = m.*t11.*3.0;
t17 = -t16;
t18 = t4+t6+t17;
t19 = 1.0./t18;
t20 = t19.^2;
A = reshape([0.0,0.0,0.0,0.0,1.0,-t13.*t19.*(D_x.*l.*4.0+l.*m.*q4.*t12.*(3.0./2.0)),0.0,t14.*t15.*t19.*(l.*q4.*t3.*t7+D_x.*l.*m.*t2+M.*l.*m.*q4.*t3).*3.0,0.0,-t13.*t19.*(D_theta.*q4.*t3.*3.0+g.*l.*m.*t10.*3.0-m.*t2.*t5.*t9.*4.0+l.*m.*q2.*q4.*t10.*3.0)+m.*t2.*t3.*t13.*t20.*(D_x.*l.*q2.*4.0-D_theta.*q4.*t2.*3.0+g.*l.*m.*t12.*(3.0./2.0)-m.*t3.*t5.*t9.*4.0+l.*m.*q2.*q4.*t12.*(3.0./2.0)).*6.0,0.0,t14.*t15.*t19.*(g.*l.*t2.*t7-t5.*t7.*t9.*t10+M.*g.*l.*m.*t2-D_x.*l.*m.*q2.*t3+l.*q2.*q4.*t2.*t7+M.*l.*m.*q2.*q4.*t2).*3.0-t2.*t3.*t14.*t20.*(-D_theta.*M.*q4-D_theta.*m.*q4+g.*l.*t3.*t7-(t5.*t7.*t9.*t12)./2.0+M.*g.*l.*m.*t3+D_x.*l.*m.*q2.*t2+l.*q2.*q4.*t3.*t7+M.*l.*m.*q2.*q4.*t3).*1.8e+1,0.0,t13.*t19.*(D_theta.*t2.*3.0-l.*m.*q2.*t12.*(3.0./2.0)+m.*q4.*t3.*t5.*8.0),1.0,t14.*t15.*t19.*(D_theta.*m+D_theta.*M-l.*q2.*t3.*t7+q4.*t5.*t7.*t12-M.*l.*m.*q2.*t3).*-3.0],[4,4]);
end


function B = B(M,l,m,q3)
%B
%    B = B(M,L,M,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    11-Feb-2022 22:15:13

t2 = cos(q3);
t3 = M.*4.0;
t4 = m.*4.0;
t5 = t2.^2;
t6 = m.*t5.*3.0;
t7 = -t6;
t8 = t3+t4+t7;
t9 = 1.0./t8;
B = [0.0;t9.*4.0;0.0;(t2.*t9.*-3.0)./l];
end

